### ISSUE TITLE
how to reproduce LiMn0.5Fe0.5PO4's precursor

### ISSUE THREAD

**Issue by YamamotoTomiya** [CederGroupHub/SynthesisSimilarity#2]
### Version

latest

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [x] Linux

### What happened?

Hi, thanks for your great work
I tried to reproduce table.3 in paper by running scripts/_01_synthesis_recommendation.
but when I use LiMn0.5Fe0.5PO4 as a target material ,the result not consistent with the paper like this
<img width="439" alt="スクリーンショット 2023-11-27 16 44 28" src="https://github.com/CederGroupHub/SynthesisSimilarity/assets/71494868/601f241d-eaff-4669-8702-d6941e3b2a10">

Would you fix this error or tell me how do I deal with this problem

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhugeyicixin** [comment]
Hi Yamamoto, thanks for playing with our repo! The material formulas in the output might appear different from their typical forms because we utilize the pymatgen package to normalize these formulas so that we can more easily compare if two materials with different written forms are identical. In the following screenshot, Fe(CO2)2 is actually the same as FeC2O4, LiP(HO2)2 is the same as LiH2PO4, and MnH6(CO)4 is the same as Mn(CH3COO)2. These are the predictions shown in Table 3. We are developing a web app to simplify the use of this synthesis predictor, where many material formulas are reformatted to their usual forms, though this may not apply to all of them. It's also expected to produce better predictions by using all data as the knowledge base and incorporating reaction balance as an additional screening criterion (by setting all_to_knowledge_base=True and validate_reaction=True as the example at https://github.com/CederGroupHub/SynthesisSimilarity/blob/master/SynthesisSimilarity/examples/synthesis_recommendation.py). You may want to try it at https://matsynthesis.org/synthesis_prediction. Thanks again for your question!

![image](https://github.com/CederGroupHub/SynthesisSimilarity/assets/5796237/4a8842c3-8cdc-4c7c-8fd9-2f4a06030387)

**Comment by YamamotoTomiya** [comment]
Thank you for your kind reply . Besides I apologize for the delayed response. 
Now I understand the differences.
thanks again
